name: main
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v2
        with:
          node-version: "16.4"

      - run: yarn
      - run: yarn build
